[versions]

# plugins
shadow = "9.3.0"

socialismus = "dev-4260d2c"

# compile time processing
lombok = "1.18.42"

# general
adventure = "4.25.0"
packetevents = "2.11.0"
cloud = "2.0.0"

# testing
junit = "6.0.1"
mockito = "5.21.0"

[libraries]

socialismus = { group = "me.whereareiam", name = "Socialismus", version.ref = "socialismus" }

# compile time processing
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

# general
adventure = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
packetevents = { group = "com.github.retrooper", name = "packetevents-spigot", version.ref = "packetevents" }

# cloud
cloud-annotations = { group = "org.incendo", name = "cloud-annotations", version.ref = "cloud" }

# testing
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-platform = { group = "org.junit.platform", name = "junit-platform-launcher" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-junit = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockito" }

[bundles]

testing = ["junit-jupiter", "mockito-core", "mockito-junit"]

[plugins]

shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }